// Historical keys retained only for backup/draft compatibility. They are no longer editable or rendered.
export const retiredInterfaceText: readonly string[] = [
  ' Early → late CPU: {value1} → {value2}ms; frame interval: {value3} → {value4}ms (first/last {value5}s).',
  ' GPU timing is unavailable for this pair; smoothness and CPU timing are still useful.',
  ' GPU timing is unavailable or still waiting for samples.',
  ' Rendering is paused; these are retained samples.',
  ' Top 8 of {value1} groups shown.',
  ' Unattributed counts are unavailable for this pass.',
  ' Unattributed: {calls} calls.',
  "'",
  ',',
  '.',
  '/',
  '0',
  '1',
  '1. Record the normal scene',
  '10 seconds · quick check',
  '100% is the default.',
  '1× is the current site speed. Closing restores 1× from this point. Nothing is saved.',
  '2',
  '2. Compare one change',
  '3',
  '3. Review the result',
  '30 seconds · longer run',
  '4',
  '5',
  '6',
  '60 seconds · sustained run',
  '7',
  '8',
  '9',
  ';',
  '=',
  'A',
  'A WORKING NOTEBOOK',
  'A capture has no rendered frames; the comparison is inconclusive.',
  'About',
  'Actual draw calls and triangles per pass. Choose the workload to rank; counts are not GPU time.',
  'Advanced: parts, render settings and data',
  'Alt',
  'Annotations',
  'Ao cached',
  'Ao camera angle',
  'Ao camera position',
  'Ao composite',
  'Ao dirty',
  'Ao geometry change',
  'Ao legacy model motion',
  'Ao legacy settling',
  'Ao projection',
  'Ao refresh',
  'Ao roll',
  'At least one result covers only part of its recording. Check the retained window.',
  'Audit trace',
  'Automatic',
  'Available on wider screens with shadows and contact shading on.',
  'B',
  'Back',
  'Background',
  'Background update',
  'Baseline',
  'Baseline again',
  'Breakdown',
  'Build / Three.js',
  'C',
  'COM / 01',
  'COM / {number}',
  'CPU and GPU timing breakdown',
  'CPU averages include frames where a phase did not run. GPU values are per sampled execution. CPU and GPU overlap; do not add them.',
  'CPU is mean preparation time per frame. GPU shows mean / p95 for the whole spacecraft draw; p95 exposes slower samples, not confidence or measurement error. Missing GPU timing stays unavailable.',
  'CPU measures JavaScript and render submission, not GPU time. Browser metrics do not measure temperature or power. Diagnostics add overhead. Compare normal → one change → normal at the same viewport and browser profile. Captures stay in this session until downloaded; closing diagnostics or reloading clears them.',
  'CPU ms',
  'CPU preparing · ms',
  'Camera',
  'Cancel',
  'Caps',
  'Capture / change',
  'Capture cancelled.',
  'Capture cancelled: diagnostic changed.',
  'Capture cancelled: diagnostics closed.',
  'Capture cancelled: measurements restarted ({value1}).',
  'Capture cancelled: normal rendering restored.',
  'Capture cancelled: page was hidden. Keep it visible for a complete recording.',
  'Capture cancelled: spacecraft filter changed.',
  'Capture cancelled: the renderer became unavailable.',
  'Capture cancelled: visibility, diagnostic or spacecraft filter changed.',
  'Capture length',
  'Capture lengths differ. Use the same length for both runs.',
  'Capture name',
  'Capture saved. Choose one change and record it at the same view and capture length. All timings and retained-window details are in Saved captures.',
  'Case studies',
  'Cast shadows inside the cabins and across the hull.',
  'Change to compare',
  'Channel standby',
  'Close Earth playback',
  'Close diagnostics',
  'Close playback panel',
  'Close rendering controls',
  'Close scene diagnostics',
  'Collapse',
  'Collapse rendering controls',
  'Collapse scene diagnostics',
  'Compare the appearance live. Changes stay when you close this panel.',
  'Contact',
  'Contact shading',
  'Css render',
  'Ctrl',
  'Current value',
  'Custom',
  'Custom capture',
  'D',
  'DPR / device DPR',
  'Del',
  'Design',
  'Diagnostic active: {value1} · {value2}. Restore normal when finished.',
  'Download JSON',
  'Download report',
  'Download report JSON',
  'Downloaded 1 saved capture and the current snapshot.',
  'Downloaded {count} saved captures and the current snapshot.',
  'Draw calls',
  'Draw calls and scene workload',
  'Draw fewer pixels',
  'Drawing at {density}× · {size} pixels. Interface text stays sharp.',
  'Drawing buffer',
  'E',
  'EUROPE AT NIGHT',
  'Earth and sky',
  'Earth playback',
  'End',
  'Enter',
  'Environment and scene',
  'Esc',
  'Expand',
  'Expand rendering controls',
  'Explore one seamless loop. Drag the timeline to pause at any point.',
  'Exterior light',
  'F',
  'F1',
  'F10',
  'F11',
  'F12',
  'F2',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  'F9',
  'FLIGHT RECORDS',
  'FPS',
  'FPS is how often the page draws. CPU prepares each frame; GPU draws the spacecraft. These are work timings, not a device rating.',
  'FR–{number}',
  'Field',
  'Find what keeps the page busy, then compare one change at a time.',
  'For example: overview, pointer still',
  'Frame',
  'Frame p95 ms',
  'Full loop in {time} at {speed}×.',
  'Full spacecraft',
  'G',
  'GPU drawing ship · ms',
  'GPU phases',
  'GPU timing: {value1}. No valid GPU samples; CPU time is not a substitute.',
  'Group',
  'Group to compare',
  'H',
  'Half drawing resolution',
  'Hidden',
  'Hide JSON',
  'Hide one room or part',
  'Hide selected group',
  'Hide the animated background',
  'Hide the whole spacecraft',
  'High · 2048',
  'Higher values soften shadow edges. {value}× is the default.',
  'Hold the same view, record a baseline, then try one change. Keep this panel collapsed during captures.',
  'Home',
  'Html sync',
  'I',
  'Ideas. Systems. People. Progress.',
  'J',
  'K',
  'Keep the view still. This gives us a reference for the work your browser is doing.',
  'L',
  'Ladder bay',
  'Ladder lights',
  'Largest CPU phases',
  'Latest saved: “{value1}”\nNo complete comparison pair is available yet.',
  'Latest saved: “{value1}” (not part of this comparison).\nReviewing an earlier comparison:',
  'Legacy metrics',
  'Loading Earth…',
  'Longer runs can reveal changes over time; they cannot identify temperature or power use. Each capture starts after a 3 second warmup.',
  'Look a little closer.',
  'Loop position',
  'Low · 512',
  'M',
  'Main spacecraft',
  'Make',
  'Material only model motion',
  'Matrices',
  'Mean calls',
  'Mean ms',
  'Mean triangles',
  'Medium · 1024',
  'Model update',
  'More than one rendering change is active. Compare one change at a time.',
  'Movement or interaction occurred. Repeat the same action, or compare two still views.',
  'N',
  'NO LINK ASSIGNED',
  'NOTES FROM THE EVERYDAY',
  'Navigation',
  'No draws recorded for this pass in the current window.',
  'Normal rendering',
  'Normal rendering · baseline',
  'O',
  'OBSERVATIONS & IDEAS',
  'OPEN TO CONNECT',
  'Off',
  'On',
  'Only',
  'Open',
  'Open Earth playback',
  'Open rendering controls',
  'Open scene diagnostics',
  'Optional capture name',
  'P',
  'Parts',
  'Pass',
  'Pause',
  'Performance check',
  'Performance report JSON',
  'PgDn',
  'PgUp',
  'Phase',
  'Pixel density',
  'Play',
  'Playback speed',
  'Pointer feedback',
  'Projects',
  'Q',
  'R',
  'Rank by',
  'Ranked by CPU time per rendered frame; p95 is per execution.',
  'Ready · 3 second warmup before each capture.',
  'Record 10 seconds',
  'Record a baseline first.',
  'Record baseline',
  'Record baseline again',
  'Record current settings',
  'Record the full scene, hide one group, then record again at the same view and settings. Compare elapsed CPU and spacecraft GPU time in Saved captures; repeat the full scene to check the result.',
  'Record this change',
  'Recording stopped. No partial capture was saved.',
  'Recording · {value1}s left',
  'Recording “{value1}” · {value2}s remaining.',
  'Reduced motion is on. Use the timeline to preview still frames.',
  'Render one frame, then pause',
  'Render pass',
  'Rendering',
  'Reset defaults',
  'Restart',
  'Restart at normal speed',
  'Restore normal',
  'Reuse stationary pixels while moving parts stay live.',
  'Reviewing these captures:',
  'Room',
  'Room lights',
  'Rooms',
  'S',
  'STANDBY',
  'Samples',
  'Saved captures (0 of 6)',
  'Saved captures ({value1} of 6)',
  'Saved “{value1}” · {value2}s, {value3} frames.',
  'Scene diagnostics',
  'Scene performance diagnostics',
  'Scene tools',
  'Setting',
  'Shadow detail',
  'Shadow softness',
  'Shadows',
  'Shared assemblies',
  'Shift',
  'Ship GPU mean / p95 ms',
  'Show all groups',
  'Show only selected group',
  'Show top 8 groups',
  'Skip background',
  'Skip contact shading',
  'Skip spacecraft rendering',
  'Small',
  'Smoothness · FPS',
  'Spacecraft',
  'Spacecraft caching',
  'Spacecraft group',
  'Spacecraft visibility',
  'Spacecraft workload',
  'Starting in {value1}s…',
  'Stay',
  'Stop',
  'Stop recording',
  'Summary ready. Copy the selected JSON; Download JSON includes raw frames and batch inventory.',
  'Sunlight on the hull and through the openings.',
  'T',
  'Tab',
  'Temporarily remove one source of work, then repeat the same view.',
  'Temporary diagnostic',
  'Temporary for this visit. Reload restores defaults.',
  'The animated background behind the spacecraft.',
  'The existing worklights in the ladder bay.',
  'The half-resolution experiment did not change the drawing buffer.',
  'The reference capture did not use the full normal scene.',
  'The repeated baseline drifted. Conditions changed during the test, so repeat before attributing a difference to the selected change. These timings do not identify the cause.',
  'The repeated baseline has not restored the full normal scene.',
  'The view and settings match, and the repeated baseline is reasonably close. Compare the timings below; repeat the test before choosing an optimization.',
  'The view and settings match. Record the baseline again to check for drift before drawing a conclusion.',
  'The warm fixtures in all four rooms.',
  'The {value1} changed.',
  'Time per sampled execution · {value1} · {value2} pending. GPU means are not amortized across all frames.',
  'Tools',
  'Treat this comparison as inconclusive. {value1}',
  'Triangles',
  'Turn off contact shading',
  'Turn shadows on to adjust their softness.',
  'Turn shadows on to compare their detail.',
  'U',
  'UPLINK',
  'Unavailable',
  'Unavailable in this browser’s graphics context.',
  'Unavailable with cabin shadow lights.',
  'Unclassified room',
  'Use my Advanced settings',
  'Use the same capture length, view and browser settings.',
  'V',
  'VOICE',
  'View JSON',
  'Viewport',
  'W',
  'Waiting for rendered frames. GPU timing may not be available in this browser.',
  'Warming up · recording starts in {value1}s.',
  'Website',
  'Which spacecraft parts create the most work?',
  'X',
  'Y',
  'Your captures will appear here. Repeat the normal scene after a change to check whether the reference has drifted.',
  'Z',
  '[',
  '\\',
  ']',
  '`',
  'archive furniture',
  'available',
  'background setting',
  'browser',
  'build',
  'cabin pressure structure',
  'camera angle',
  'camera position',
  'chassis interior wall',
  'communications batches',
  'contact shading resolution',
  'contact shading sample count',
  'contact shading setting',
  'context-lost',
  'curious.',
  'denoising sample count',
  'deployable reader',
  'disjoint',
  'display scaling',
  'disposed',
  'docking sleeve and hatch',
  'doors and passage assemblies',
  'drawing buffer size',
  'exterior light brightness',
  'flight-console furniture',
  'interior fittings',
  'journal',
  'ladder light brightness',
  'mixed cabin fixtures',
  'mixed service bus and appendages',
  'motion setting',
  'ms/frame',
  'not recorded yet',
  'notes',
  'other or mixed batches',
  'outboard wall equipment',
  'outer chassis',
  'p95 ms',
  'personal-study furniture',
  'pressure structure',
  'render pixel ratio',
  'render quality setting',
  'renderer version',
  'reported CPU thread count',
  'room',
  'room light brightness',
  'roomSurface',
  'shadow resolution',
  'shadow setting',
  'shadow softness',
  'shared',
  'signage and label batches',
  'solar array batches',
  'spacecraft caching setting',
  'systems',
  'things.',
  'unavailable',
  'useful',
  'utility fittings',
  'viewport size',
  'workshop furniture',
  '{percent} percent',
  '{size} × {size}. Lower detail gives coarser shadow edges.',
  '{speed} times the normal site speed',
  '{state} · Soft darkness at corners and where surfaces meet.',
  '{time} of {duration}',
  '{value1}\nBaseline: “{value2}”\nChange: “{value3}”\nBaseline again: {value4}',
  '{value1} pass samples · {value2} total calls / {value3} triangles per pass.{value4}{value5}',
  '{value1} scene diagnostics',
  '{value1}: {value2}s of {value3}s retained.{value4}',
  '{value1}s live window · slower frames (p95): {value2}ms.{value3}{value4}',
  '{value} times',
  '←',
  '↑',
  '→',
  '↓',
  '−',
  '⌘',
];
